//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by mod_creatureinfo.rc
//
#define IDD_SENDSTATS                   171
#define IDD_CONFIG                      3002
#define IDD_NAME                        3003
#define IDC_ENABLE                      3004
#define IDD_INFO                        3004
#define IDC_TOOLCREATURINFO_PLAYER_1LINE 3012
#define IDC_TOOLCREATURINFO_PLAYER_2LINE 3013
#define IDC_TOOLCREATURINFO_MONSTER_1LINE 3014
#define IDC_TOOLCREATURINFO_MONSTER_2LINE 3015
#define IDC_TOOLCREATURINFO_SELF_1LINE  3016
#define IDC_TOOLCREATURINFO_SELF_2LINE  3017
#define IDC_TOOLCREATURINFO_MONSTER_UNIQUEMONSTERNAMES 3018
#define IDC_TOOLCREATURINFO_NAMECHANGER 3019
#define IDC_TOOLCREATURINFO_KNOWNINFO   3020
#define IDC_TOOLCREATURINFO_LIST        3021
#define IDC_TOOLCREATURINFO_REFRESH     3024
#define IDC_TOOLCREATURINFO_RELPOS      3025
#define IDC_TOOLCREATURINFO_ADVANCED    3026
#define IDC_TOOLCREATURINFO_BATTLEONLY  3027
#define IDC_TOOLCREATURINFO_SELF        3027
#define IDC_TOOLCREATURINFO_MONSTER     3028
#define IDC_TOOLCREATURINFO_PLAYER      3029
#define IDC_TOOLCREATURINFO_ALLINFO     3030
#define IDC_TOOLCREATURINFO_INFO_PLAYERS 3031
#define IDC_TOOLCREATURINFO_ADDITIONALREQUEST 3031
#define IDC_TOOLCREATURINFO_INFO_MONSTERS 3032
#define IDC_TOOLCREATURINFO_INFO_NAME   3034
#define IDC_TOOLCREATURINFO_INFO_TYPE   3035
#define IDC_TOOLCREATURINFO_INFO_HP     3036
#define IDC_TOOLCREATURINFO_INFO_VOC    3037
#define IDC_TOOLCREATURINFO_INFO_LEVEL  3038
#define IDC_TOOLCREATURINFO_INFO_GUILDNAME 3039
#define IDC_TOOLCREATURINFO_INFO_GUILDRANK 3040
#define IDC_TOOLCREATURINFO_INFO_GUILDDESCRIPTION 3041
#define IDC_TOOLCREATURINFO_INFO_TXTVOC 3042
#define IDC_TOOLCREATURINFO_INFO_TXTLEVEL 3043
#define IDC_TOOLCREATURINFO_INFO_COMBO  3046
#define IDC_COLLECT_STATS               3047
#define IDC_SHOW_CREATURES_IN_AREA      3048
#define IDC_RANGE_XY                    3049
#define IDC_TOOLCREATURINFO_INFO_LAST   3050
#define IDC_RANGE_Z                     3050
#define IDC_TOOLCREATURINFO_SELF_WINDOW 3051
#define IDC_TOOLCREATURINFO_SELF_TRAY   3052
#define IDC_FRAME_PLAYER_INFO           3053
#define IDC_FRAME_SELF_INFO             3054
#define IDC_FRAME_CREATURE_DETECTION    3055
#define IDC_FRAME_MONSTERS_INFO         3056

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        3006
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         3057
#define _APS_NEXT_SYMED_VALUE           3000
#endif // ifndef APSTUDIO_READONLY_SYMBOLS
#endif // ifdef APSTUDIO_INVOKED
