//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by tibiaauto.rc
//
#define IDS_BEGIN                       1
#define IDS_SKILL                       2
#define IDS_RESOURCE                    3
#define IDS_PROXIMITY                   4
#define IDS_ITEM                        5
#define IDS_GENERAL                     6
#define IDS_SKILL_ALL                   7
#define IDS_SKILL_LEVEL                 8
#define IDS_SKILL_MAGICLVL              9
#define IDS_SKILL_FISHING               10
#define IDS_SKILL_FIST                  11
#define IDS_SKILL_CLUB                  12
#define IDS_SKILL_SWORD                 13
#define IDS_SKILL_AXE                   14
#define IDS_SKILL_DISTANCE              15
#define IDS_SKILL_SHIELDING             16
#define IDS_RESOURCE_HP                 17
#define IDS_RESOURCE_MP                 18
#define IDS_RESOURCE_SP                 19
#define IDS_RESOURCE_STAMINA            20
#define IDS_RESOURCE_CAPACITY           21
#define IDS_RESOURCE_SPACE              22
#define IDS_ITEM_FOOD                   23
#define IDS_ITEM_CUSTOM                 24
#define IDS_PROXIMITY_PLAYER            25
#define IDS_PROXIMITY_MONSTER           26
#define IDS_PROXIMITY_GM                27
#define IDS_PROXIMITY_BATTLELIST        28
#define IDS_PROXIMITY_SKULL             29
#define IDS_GENERAL_ALLMESSAGES         30
#define IDS_GENERAL_PUBLICMESSAGES      31
#define IDS_GENERAL_PRIVATEMESSAGES     32
#define IDS_GENERAL_CHARACTERMOVED      33
#define IDS_GENERAL_STATUSFLAG          34
#define IDS_BEGIN_ATTRIBUTE             35
#define IDS_LEVELUP                     36
#define IDS_PERCLVLACHIEVED             37
#define IDS_PERCLVLREMAINING            38
#define IDS_CONDITION                   39
#define IDS_EQUAL                       40
#define IDS_LESS                        41
#define IDS_MORE                        42
#define IDS_NEARBY                      43
#define IDS_DISAPPEARS                  44
#define IDS_ISONSCREENFOR               45
#define IDS_KILL                        46
#define IDS_SHUTDOWN                    47
#define IDS_RUNAWAY                     48
#define IDS_START                       49
#define IDS_DEPOT                       50
#define IDS_SPELL                       51
#define IDS_SCREENSHOT                  52
#define IDS_SUSPEND_MODULES             53
#define IDS_START_MODULES               54
#define IDS_SOUND                       55
#define IDS_ATTACK                      56
#define IDS_STOPWALKING                 56
#define IDS_LOGOUT                      57
#define IDS_MAXIMIZE                    58
#define IDS_WINDOW_ACTION               58
#define IDS_LOG_EVENTS                  59
#define IDS_FROMALL                     60
#define IDS_FROM                        61
#define IDS_CONTAINS                    62
#define IDS_RESOURCE_XP                 63
#define IDS_ONLINE                      65
#define IDS_ONLINE_CURRENT_PLAYER       66
#define IDS_ONLINE_NONE                 67
#define IDS_ONLINE_HEART                68
#define IDS_ONLINE_SKULL                69
#define IDS_ONLINE_LIGHTNING            70
#define IDS_ONLINE_RETICLE              71
#define IDS_ONLINE_STAR                 72
#define IDS_ONLINE_YINYANG              73
#define IDS_ONLINE_TRIPOINT             74
#define IDS_ONLINE_X                    75
#define IDS_ONLINE_DOLLARSIGN           76
#define IDS_ONLINE_IRONCROSS            77
#define IDS_LOGON                       78
#define IDS_LOGOFF                      79
#define IDS_PROXIMITY_SKULL_BLACK       80
#define IDS_PROXIMITY_SKULL_RED         81
#define IDS_PROXIMITY_SKULL_GREEN       82
#define IDS_PROXIMITY_SKULL_WHITE       83
#define IDS_PROXIMITY_SKULL_YELLOW      84
#define IDS_STATUS                      85
#define IDS_STATUS_POISONED             86
#define IDS_STATUS_BURNING              87
#define IDS_STATUS_ELECTRIFIED          88
#define IDS_STATUS_DRUNK                89
#define IDS_STATUS_MANASHIELD           90
#define IDS_STATUS_SLOWED               91
#define IDS_STATUS_HASTED               92
#define IDS_STATUS_FREEZING             93
#define IDS_STATUS_DROWNING             94
#define IDS_STATUS_DAZZLED              95
#define IDS_STATUS_CURSED               96
#define IDS_STATUS_STRENGTHENED         97
#define IDS_STATUS_LOGOUTBLOCK          98
#define IDS_STATUS_PZBLOCK              99
#define IDS_STATUS_INPZ                 100
#define IDS_ALARM_TYPE_ERROR            101
#define IDD_TIBIAAUTO_DIALOG            102
#define IDS_ATTRIBUTE_ERROR             102
#define IDS_CONDITION_ERROR             103
#define IDS_TRIGGER_ERROR               104
#define IDS_SPELLWORDS_ERROR            105
#define IDS_SOUNDFILE_ERROR             106
#define IDS_SCREENSHOT_ERROR            107
#define IDS_GENERAL_CHARACTERHIT        108
#define IDD_COLORCHOOSER_DIALOG         109
#define IDS_WINDOWACTION_ERROR          109
#define IDS_GENERAL_CHARACTERNOTMOVED   110
#define IDS_PRESENT                     111
#define IDS_ABSENT                      112
#define IDS_ONLINE_VIP_PLAYER           113
#define IDR_MAINFRAME                   128
#define IDD_CHAR_DIALOG                 130
#define IDD_TOOL_RUNEMAKER              131
#define IDD_TOOL_CONTAINERCONTENT       133
#define IDD_TOOL_CHARINFO               134
#define IDD_TOOL_MONSTERSHOW            135
#define IDD_TOOL_AUTOGO                 136
#define IDD_TOOL_AUTOFISH               138
#define IDD_TOOL_AUTOUH                 140
#define IDD_TOOL_AUTOATTACK             142
#define IDD_TOOL_AUTOGROUP              143
#define IDD_TOOL_MAPSHOW                144
#define IDD_TOOL_SPELLCASTER            146
#define IDD_TOOL_AUTOAIM                148
#define IDD_TOOL_MEMDEBUG               150
#define IDB_BITMAP1                     151
#define IDD_TOOL_FLUIDDRINKER           152
#define IDD_TOOL_TRADEMON               154
#define IDD_TOOL_ITEMCONFIG             156
#define IDD_TOOL_AMMORESTACK            157
#define IDD_TOOL_AUTORESPOND            159
#define IDD_LOADED_MODULES              160
#define IDD_CONFIGSTATUS                161
#define IDR_LOADED_MODULES_MENU         163
#define IDD_DONATION                    171
#define IDD_ENTERCODE                   175
#define IDD_PYTHON_SCRIPTS              179
#define IDR_PYTHON_SCRIPTS_FUNLIST_MENU 180
#define IDR_PYTHON_SCRIPTS_MENU         181
#define IDD_SCRIPT_CONFIG               182
#define IDD_OPTIONS                     183
#define IDC_EDIT_ADDRESS                1000
#define IDC_EDIT_ADDRESS_RES_DEC        1001
#define IDC_SCAN                        1004
#define IDC_ERROR                       1005
#define IDC_EDIT_ADDRESS_RES_HEX        1006
#define IDC_EDIT_VALUE                  1007
#define IDC_VALUE_RES_LIST              1008
#define IDC_LIGHT                       1010
#define IDC_TOOL_AUTOGROUP              1011
#define IDC_TOOL_AUTOUH                 1012
#define IDC_TEST                        1013
#define IDC_TOOL_INJECTMC               1013
#define IDC_TEST2                       1014
#define IDC_TOOL_EATER                  1014
#define IDC_CHAR_LIST                   1015
#define IDC_TOOL_MAPSHOW                1015
#define IDC_TOOL_AUTOATTACK             1016
#define IDC_TOOL_RUNEMAKER              1017
#define IDC_TOOL_ANTILOG                1018
#define IDC_TOOL_SPELLCASTER            1019
#define IDC_TOOL_RUNEMAKER_TOEXTERNAL   1020
#define IDC_TOOL_LOGIN                  1020
#define IDC_TOOL_RUNEMAKER_TOSAFE       1021
#define IDC_FPS                         1021
#define IDC_TOOL_RUNEMAKER_ENABLE       1022
#define IDC_TOOL_SORTER                 1022
#define IDC_TOOL_RUNEMAKER_RUNESPELL    1023
#define IDC_TOOL_BANKER                 1023
#define IDC_TOOL_RUNEMAKER_MANA         1024
#define IDC_TOOL_RUNEMAKER_MANA_INFO    1025
#define IDC_TOOL_RUNEMAKER_EXTERNAL     1026
#define IDC_TOOL_RUNEMAKER_SAFE         1027
#define IDC_EXIT                        1027
#define IDC_TOOL_RUNEMAKER_SOUL         1028
#define IDC_CONTAINERCONTENT_LIST       1029
#define IDC_TOOL_CHARINFO               1030
#define IDC_CHARINFO_HP                 1031
#define IDC_CHARINFO_MANA               1032
#define IDC_TOOL_AUTOEAT_ENABLE         1033
#define IDC_CHARINFO_EXP                1033
#define IDC_CHARINFO_SHIELD             1034
#define IDC_CHARINFO_SWORD              1035
#define IDC_CHARINFO_CLUB               1036
#define IDC_CHARINFO_AXE                1037
#define IDC_TOOL_MONSERSHOW             1038
#define IDC_MONSTERSHOW_MONSTERNIFO     1039
#define IDC_TOOL_TRADEMON               1039
#define IDC_TOOL_MAPHACK                1040
#define IDC_TOOL_XRAY                   1041
#define IDC_MONSTERSHOW_FREEZE          1042
#define IDC_TOOL_CREATUREINFO           1042
#define IDC_TOOL_AUTOGO                 1043
#define IDC_TOOL_TEAM                   1044
#define IDC_AUTOGO_TRIGGER              1046
#define IDC_AUTOGO_ACTION               1047
#define IDC_AUTOGO_RUNAWAY_X            1048
#define IDC_AUTOGO_RUNAWAY_Y            1049
#define IDC_AUTOGO_RUNAWAY_Z            1050
#define IDC_CHARINFO_EXP_SPEED          1050
#define IDC_AUTOGO_ACT_X                1051
#define IDC_CHARINFO_SHIELD_SPEED       1051
#define IDC_AUTOGO_ACT_Y                1052
#define IDC_CHARINFO_SWORD_SPEED        1052
#define IDC_AUTOGO_ACT_Z                1053
#define IDC_TOOL_AUTOATTACK_CURY        1053
#define IDC_CHARINFO_CLUB_SPEED         1053
#define IDC_AUTOGO_ENABLE               1054
#define IDC_TOOL_AUTOATTACK_CURZ        1054
#define IDC_CHARINFO_AXE_SPEED          1054
#define IDC_TOOL_AUTOFISH               1055
#define IDC_AUTOGO_CUR_X                1055
#define IDC_AUTOFISH_WHENCAP            1056
#define IDC_AUTOGO_CUR_Y                1056
#define IDC_CHARINFO_DIST               1056
#define IDC_AUTOFISH_QTY                1057
#define IDC_AUTOGO_CUR_Z                1057
#define IDC_CHARINFO_DIST_SPEED         1057
#define IDC_AUTOFISH_TIME               1058
#define IDC_CHARINFO_FISH               1058
#define IDC_AUTOFISH_ENABLE             1059
#define IDC_CHARINFO_FISH_SPEED         1059
#define IDC_AUTOGO_TORUNAWAY            1060
#define IDC_CHARINFO_EXP_UPIN           1060
#define IDC_AUTOGO_GOORDER              1061
#define IDC_AUTOGO_TOSTART              1061
#define IDC_CHARINFO_SHIELD_UPIN        1061
#define IDC_AUTOGO_GOORDER_DOWN         1062
#define IDC_CHARINFO_SWORD_UPIN         1062
#define IDC_AUTOGO_GOORDER_UP           1063
#define IDC_TOOL_RUNEMAKER_INFO         1063
#define IDC_CHARINFO_CLUB_UPIN          1063
#define IDC_TOOL_CHARINFO_INFO          1064
#define IDC_CHARINFO_AXE_UPIN           1064
#define IDC_TOOL_MONSERSHOW_INFO        1065
#define IDC_CHARINFO_DIST_UPIN          1065
#define IDC_TOOL_AUTOGO_INFO            1066
#define IDC_CHARINFO_FISH_UPIN          1066
#define IDC_TOOL_AUTOFISH_INFO          1067
#define IDC_LIGHT_INFO                  1068
#define IDC_SAVE                        1069
#define IDC_TOOL_AUTOGROUP_INFO         1070
#define IDC_LOAD                        1071
#define IDC_LOGINNAME                   1072
#define IDC_TOOL_RUNEMAKER_INFO_BLANKS  1073
#define IDC_TOOL_AUTOUH_INFO            1073
#define IDC_TOOL_RUNEMAKER_INFO_FOOD    1074
#define IDC_TOOL_MAPSHOW_INFO           1074
#define IDC_TOOL_AUTOGROUP_ENABLE       1074
#define IDC_TOOL_ITEMCONFIG             1074
#define IDC_TOOL_SELLER                 1075
#define IDC_TOOL_RUNEMAKER_INFO_RUNETIME 1075
#define IDC_TOOL_AUTOATTACK_INFO        1075
#define IDC_TOOL_AUTOGROUP_BETWEENCONT  1075
#define IDC_TOOL_AUTOATTACK_MONSTER     1076
#define IDC_TOOL_AUTORESPOND_INFO       1076
#define IDC_TOOL_SPELLCASTER_INFO       1077
#define IDC_TOOL_AUTOAIM_INFO           1078
#define IDC_TOOL_AUTOATTACK_MONSTERLIST 1079
#define IDC_TOOL_FLUIDDRINKER_INFO      1079
#define IDC_TOOL_AUTOATTACK_ADD_MONSTER 1080
#define IDC_TOOL_AMMORESTACK_INFO       1080
#define IDC_TOOL_AUTOATTACK_REMOVE_MONSTER 1081
#define IDC_TOOL_AUTOLOOTER_INFO        1081
#define IDC_TOOL_AUTOATTACK_ENABLE      1082
#define IDC_LOADED_MODULES              1082
#define IDC_TOOL_AUTOATTACK_WAYPOINTLIST 1083
#define IDC_TOOL_MAPHACK_INFO           1083
#define IDC_TOOL_AUTOATTACK_ADD_WAYPOINT 1084
#define IDC_PYTHON_SCRIPTS              1084
#define IDC_TOOL_AUTOUH_ENABLE          1085
#define IDC_TOOL_AUTOATTACK_REMOVE_WAYPOINT 1085
#define IDC_TOOL_AUTOUH_SLEEP           1086
#define IDC_TOOL_AUTOUH_HPTRIGGER       1087
#define IDC_TOOL_SPELLCASTER_MANA       1087
#define IDC_TOOL_SPELLCASTER_SPELL      1088
#define IDC_TOOL_AUTOUH_GRP_HPBELOW     1088
#define IDC_TOOL_MAPSHOW_RESEARCH       1089
#define IDC_TOOL_SPELLCASTER_HPBELOW    1089
#define IDC_TOOL_AUTOATTACK_AUTOFOLLOW  1090
#define IDC_TOOL_MAPSHOW_CLEAR          1091
#define IDC_TOOL_AUTOATTACK_AUTOLOOTFOOD 1091
#define IDC_TOOL_AUTOATTACK_CURX        1092
#define IDC_TOOL_SPELLCASTER_ENABLE     1093
#define IDC_TOOL_AUTOATTACK_NOMOVESUSPEND 1093
#define IDC_TOOL_MAPSHOW_UPDOWN         1096
#define IDC_RESET_COUNTERS              1097
#define IDC_TIME                        1098
#define IDC_AUTOAIM_ENABLE              1100
#define IDC_TOOL_AUTOAIM                1101
#define IDC_TOOL_FLUIDDRINKER           1102
#define IDC_TOOL_MEMDEBUG               1103
#define IDC_TOOL_AMMORESTACK            1104
#define IDC_ADDRESS                     1105
#define IDC_TOOL_AUTOLOOTER             1105
#define IDC_TOOL_AUTOATTACK_AUTOLOOTGP  1106
#define IDC_TOOL_AUTOATTACK_STATE_LOOT  1109
#define IDC_AUTOFISH_MOVETOCONT         1110
#define IDC_TOOL_AUTOATTACK_STATE_WALKER 1110
#define IDC_TOOL_USEARROW               1111
#define IDC_TOOL_AUTOATTACK_STATE_ATTACK 1111
#define IDC_TOOL_MAKETWO                1112
#define IDC_TOOL_FLUIDDRINKER_HPBELOW   1113
#define IDC_TOOL_FLUIDDRINKER_MANABELOW 1114
#define IDC_TOOL_FLUIDDRINKER_DRINKMANA 1115
#define IDC_TOOL_FLUIDDRINKER_DRINKHP   1116
#define IDC_TOOL_FLUIDDRINKER_ENABLE    1117
#define IDC_TOOL_FLUIDDRINKER_SLEEP     1118
#define IDC_TOOL_AUTOATTACK_MODE        1118
#define IDC_AUTOFISH_REVEAL             1119
#define IDC_TOOL_AUTOATTACK_WAYPOINTSELMODE 1119
#define IDC_TRADEMON_ENABLE             1120
#define IDC_TOOL_AUTOATTACK_MAPUSED     1120
#define IDC_MONSTERSHOW_REVEALSLIME     1122
#define IDC_TOOL_AUTOATTACK_AUTOLOOTWORMS 1123
#define IDC_TOOL_AUTOATTACK_AUTOLOOTCUSTOM 1124
#define IDC_TOOL_AUTOUH_RUNETYPE        1125
#define IDC_TOOL_AUTOATTACK_LOOTINBAGS  1125
#define IDC_TOOL_AUTOUH_FALLBACK        1126
#define IDC_TOOL_AUTOATTACK_GOUPMETHOD  1126
#define IDC_TOOL_AUTOUH_GRP_RUNETYPE    1127
#define IDC_TOOL_AUTOUH_GRP_FALLBACK    1128
#define IDC_TOOL_AUTOUH_HOTKEY          1129
#define IDC_TOOL_AUTOUH_GRP_GRP_MEMBER_REMOVE 1130
#define IDC_TOOL_AUTOUH_GRP_MEMBER_ADD  1131
#define IDC_TOOL_AUTOUH_GRP_MEMBER      1132
#define IDC_TOOL_AUTOUH_GRP_MEMBER_LIST 1133
#define IDC_TOOL_AMMORESTACK_AMMO       1134
#define IDC_TOOL_AMMORESTACK_THROWABLE  1136
#define IDC_TOOL_AMMORESTACK_AMMO_AT    1138
#define IDC_TOOL_AMMORESTACK_AMMO_TO    1139
#define IDC_TOOL_AMMORESTACK_THROWABLE_AT 1140
#define IDC_TOOL_AMMORESTACK_THROWABLE_TO 1141
#define IDC_TOOL_AMMORESTACK_ENABLE     1142
#define IDC_TOOL_FLUIDDRINKER_HOTKEY_LIFE 1143
#define IDC_TOOL_FLUIDDRINKER_HOTKEY_MANA 1144
#define IDC_TOOL_ITEMCONFIG_FOODLIST    1148
#define IDC_AUTOAIM_CREATURES           1149
#define IDC_TOOL_ARMMORESTACK_PICKUP    1153
#define IDC_TOOL_AMMORESTACK_PICKUP_UL  1154
#define IDC_RADIO                       1155
#define IDC_TOOL_ITEMCONFIG_LOOTED_LIST 1156
#define IDC_TOOL_ITEMCONFIG_ITEMS_LIST  1161
#define IDC_TOOL_AMMORESTACK_PICKUP_CL  1163
#define IDC_TOOL_AMMORESTACK_PICKUP_BL  1164
#define IDC_TOOL_AMMORESTACK_PICKUP_BC  1165
#define IDC_TOOL_AMMORESTACK_PICKUP_BR  1166
#define IDC_TOOL_ITEMCONFIG_CORPSES_LIST 1166
#define IDC_TOOL_AMMORESTACK_PICKUP_CR  1167
#define IDC_TOOL_AMMORESTACK_PICKUP_UR  1168
#define IDC_TOOL_AMMORESTACK_PICKUP_UC  1169
#define IDC_TOOL_ITEMCONFIG_REFRESH     1170
#define IDC_TOOL_AUTOATTACK_SUSPENDONENEMY 1171
#define IDC_VAL                         1173
#define IDC_TOOL_AMMORESTACK_LOOTCAPLIMIT 1175
#define IDC_TOOL_FLUIDDRINKER_DROPEMPTY 1176
#define IDC_TOOL_AUTORESPOND            1177
#define IDC_AUTORESPOND_MSGHISTORY      1181
#define IDC_AUTORESPOND_ACTIONLOG       1182
#define IDC_AUTORESPOND_ENABLE          1184
#define IDC_AUTORESPOND_SCRIPT          1186
#define IDC_AUTORESPOND_CLEAR           1187
#define IDC_BUTTON1                     1191
#define IDC_AUTORESPOND_THREADSTATUS    1192
#define IDC_AUTORESPOND_ENABLEDEBUG     1193
#define IDC_LOADEDMODULES_LIST          1194
#define IDD_CONFIGSTATUS_LOG            1195
#define IDC_AUTORESPOND_LOCALECHO       1196
#define IDC_DONATION                    1199
#define IDC_RUNTIMEID                   1200
#define IDC_CODE                        1201
#define IDC_LIST                        1203
#define IDC_FUNLIST                     1204
#define IDC_RUN_INTERPRETER             1205
#define IDC_LOAD_SCRIPT                 1206
#define IDC_SCRIPT_CONFIG_PARAM_LIST    1207
#define IDC_SCRIPT_CONFIG_PARAM_EDIT    1208
#define IDC_OPTIONS                     1209
#define IDC_SEND_LOOTSTATS              1210
#define IDC_SIZE_LOOTSTATS              1211
#define IDC_SEND_CREATURESTATS          1212
#define IDC_SIZE_CREATURESTATS          1213
#define IDC_PROGRESS                    1214
#define IDC_SEND_MAPS                   1215
#define IDC_BROWSER_ADS                 1216
#define IDC_SEND_USAGESTATS             1216
#define IDC_SIZE_USAGESTATS             1217
#define IDC_EXAMPLE_BUTTON              1218
#define IDC_SKIN                        1219
#define IDC_DETAIL_PICKER               1229
#define IDC_EXAMPLE_CHECK               1231
#define IDC_EXAMPLE_EDIT                1232
#define IDC_EXAMPLE_STATIC              1234
#define IDSAVE                          1239
#define IDC_AFK_TOOLS                   1244
#define IDC_INFORMATION_TOOLS           1245
#define IDC_CAVEBOT_TOOLS               1246
#define IDC_CONFIG                      1247
#define IDC_OTHER_TOOLS                 1248
#define IDC_FIGHT_TOOLS                 1249
#define IDC_USAGE_STATISTICS            1250
#define IDC_TIBIA_MAPS                  1251
#define IDC_CREATURE_STATISTICS         1252
#define IDC_GATHER_BOT_STATS            1253
#define IDC_LOAD_ON_STARTUP             1254
#define IDC_HIDE_TIBIA                  1255
#define IDC_SCRIPTLOAD_ASK              1256
#define IDC_SCRIPTLOAD_START            1257
#define IDC_SCRIPTLOAD_NOSTART          1258
#define IDC_LOADING_SCRIPT_OPTIONS      1260
#define IDC_RED_SLIDER_DOWN             3000
#define IDC_GREEN_SLIDER_DOWN           3001
#define IDC_BLUE_SLIDER_DOWN            3002
#define IDC_RED_SLIDER_UP               4000
#define IDC_GREEN_SLIDER_UP             4001
#define IDC_BLUE_SLIDER_UP              4002
#define IDC_RED_SLIDER                  5000
#define IDC_MONSTERSHOW_FIRST           5000
#define IDC_GREEN_SLIDER                5001
#define IDC_BLUE_SLIDER                 5002
#define IDC_RED_VALUE                   6000
#define IDC_MAPSHOW_FIRST               6000
#define IDC_GREEN_VALUE                 6001
#define IDC_BLUE_VALUE                  6002
#define IDC_FRAME                       9000
#define IDC_LOOT_STATISTICS             9000
#define IDC_SECONDARY_BACKGROUND        9999
#define ID_STOPMODULE_STARTMODULE       32771
#define ID_STOPMODULE_STOPMODULE        32772
#define ID_MODULEACTIONS_LOADCUSTOMMODULE 32773
#define ID_MODULEACTIONS_SHOWCONFIGDIALOG 32774
#define ID_PYTHONSCRIPTSFUNLISTMENU_CALL 32779
#define ID_MENU_RELOAD                  32781
#define ID_MENU_UNLOAD                  32782
#define ID_MENU_CONFIGOPTIONS           32783
#define ID_MENU_ENABLE                  32784

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        187
#define _APS_NEXT_COMMAND_VALUE         32786
#define _APS_NEXT_CONTROL_VALUE         1261
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
