//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by mod_spellcaster.rc
//
#define IDC_TOOL_SPELLCASTER_MANA       1086
#define IDC_TOOL_SPELLCASTER_MANA_MANA  1087
#define IDC_TOOL_SPELLCASTER_SPELL      1088
#define IDC_TOOL_SPELLCASTER_MANASPELL  1088
#define IDC_TOOL_SPELLCASTER_MANA_SPELL 1088
#define IDC_TOOL_SPELLCASTER_HPBELOW    1089
#define IDC_TOOL_SPELLCASTER_LIFE_HP    1089
#define IDC_TOOL_SPELLCASTER_LIFESPELL  1090
#define IDC_TOOL_SPELLCASTER_LIFE_SPELL 1090
#define IDC_TOOL_SPELLCASTER_SUMMON_LESSTHAN 1091
#define IDC_TOOL_SPELLCASTER_SUMMON_NAME 1092
#define IDC_TOOL_SPELLCASTER_SUMMON_MANA 1093
#define IDC_TOOL_SPELLCASTER_MANA_SPELL_MANA 1094
#define IDC_TOOL_SPELLCASTER_STRIKE     1094
#define IDC_TOOL_SPELLCASTER_LIFE_SPELL_MANA 1095
#define IDC_TOOL_SPELLCASTER_STRIKE_MANA 1096
#define IDC_TOOL_SPELLCASTER_STRIKE_SPELL_DEFAULT 1097
#define IDC_TOOL_SPELLCASTER_STRIKE_SPELL_DEFAULT_HP_MIN 1098
#define IDC_TOOL_SPELLCASTER_AOE_AFFECT 1099
#define IDC_TOOL_SPELLCASTER_LOGIC      1100
#define IDC_TOOL_SPELLCASTER_ALARM      1101
#define IDC_TOOL_SPELLCASTER_EXURA_LIFE 1101
#define IDC_TOOL_SPELLCASTER_GRAN_LIFE  1102
#define IDC_TOOL_SPELLCASTER_VITA_LIFE  1103
#define IDC_TOOL_SPELLCASTER_EXURA_MANA 1104
#define IDC_TOOL_SPELLCASTER_GRAN_MANA  1105
#define IDC_TOOL_SPELLCASTER_VITA_MANA  1106
#define IDC_TOOL_SPELLCASTER_MIN_POISON_DAMAGE 1107
#define IDC_TOOL_SPELLCASTER_SIO_MANA   1108
#define IDC_TOOL_SPELLCASTER_SIO_LIFE   1109
#define IDD_CONFIG                      3000
#define IDC_ENABLE                      3004
#define IDD_WHITELIST                   3004
#define IDC_TOOL_SPELLCASTER_MANA1      3014
#define IDC_TOOL_SPELLCASTER_LIFE       3015
#define IDC_TOOL_SPELLCASTER_SUMMON     3016
#define IDC_TOOL_SPELLCASTER_FLAM       3017
#define IDC_TOOL_SPELLCASTER_FRIGO      3018
#define IDC_TOOL_SPELLCASTER_MORT       3019
#define IDC_TOOL_SPELLCASTER_TERA       3020
#define IDC_TOOL_SPELLCASTER_VIS        3021
#define IDC_TOOL_SPELLCASTER_CON        3022
#define IDC_TOOL_SPELLCASTER_SAN        3023
#define IDC_TOOL_SPELLCASTER_HUR        3024
#define IDC_TOOL_SPELLCASTER_CUSTOM     3025
#define IDC_TOOL_SPELLCASTER_EXURA      3026
#define IDC_TOOL_SPELLCASTER_GRAN       3027
#define IDC_TOOL_SPELLCASTER_VITA       3028
#define IDC_TOOL_SPELLCASTER_HEAL_PARALYSIS 3029
#define IDC_TOOL_SPELLCASTER_HEAL_POISON 3030
#define IDC_TOOL_SPELLCASTER_AOE        3031
#define IDC_TOOL_SPELLCASTER_EXORI      3032
#define IDC_TOOL_SPELLCASTER_EXORI_GRAN 3033
#define IDC_ANIMATE1                    3033
#define IDC_TOOL_SPELLCASTER_EXEVO_MAS_SAN 3034
#define IDC_TOOL_SPELLCASTER_SIO        3035
#define IDC_TOOL_SPELLCASTER_EXEVO_FLAM_HUR 3036
#define IDC_TOOL_SPELLCASTER_EXEVO_VIS_HUR 3037
#define IDC_TOOL_SPELLCASTER_EXEVO_FRIGO_HUR 3038
#define IDC_TOOL_SPELLCASTER_EXEVO_TERA_HUR 3039
#define IDC_TOOL_SPELLCASTER_EXORI_MAS  3040
#define IDC_TOOL_SPELLCASTER_EXEVO_VIS_LUX 3041
#define IDC_TOOL_SPELLCASTER_EXEVO_GRAN_MAS_TERA 3042
#define IDC_TOOL_SPELLCASTER_EXEVO_GRAN_VIS_LUX 3043
#define IDC_TOOL_SPELLCASTER_EXEVO_GRAN_MAS_FLAM 3044
#define IDC_TOOL_SPELLCASTER_EXEVO_EXEVO_GRAN_MAS_VIS 3045
#define IDC_TOOL_SPELLCASTER_EXEVO_GRAN_MAS_VIS 3045
#define IDC_TOOL_SPELLCASTER_EXEVO_GRAN_MAS_FRIGO 3046
#define IDC_TOOL_SPELLCASTER_DISABLE_WARNING 3048
#define IDC_TOOL_SPELLCASTER_RANDM_CAST 3049
#define IDC_TOOL_SPELLCASTER_RANDOM_CAST 3049
#define IDC_FRAME_SUMMON_CONTROL        3050
#define IDC_FRAME_STRIKE_SPELLS         3051
#define IDC_FRAME_SORCERER_AOE          3052
#define IDC_FRAME_PALADIN_STRIKE        3053
#define IDC_FRAME_PALADIN_AOE           3054
#define IDC_FRAME_MANA                  3055
#define IDC_FRAME_LIFE                  3056
#define IDC_FRAME_MAGE_STRIKE           3057
#define IDC_FRAME_KNIGHT_STRIKE         3058
#define IDC_FRAME_KNIGHT_AOE            3059
#define IDC_FRAME_DRUID_AOE             3060
#define IDC_FRAME_AOE_SPELLS            3061
#define IDC_WHITELIST_NAME              3100
#define IDC_WHITELIST_ADD               3101
#define IDC_WHITELIST_DELETE            3102
#define IDC_WHITELIST_LIST              3103
#define IDC_TOOL_SPELLCASTER_HEAL_LIST  3104

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        3008
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         3062
#define _APS_NEXT_SYMED_VALUE           3000
#endif
#endif
