//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by mod_spellcaster.rc
//
#define IDC_TOOL_SPELLCASTER_MANA       1086
#define IDC_TOOL_SPELLCASTER_MANA_MANA  1087
#define IDC_TOOL_SPELLCASTER_SPELL      1088
#define IDC_TOOL_SPELLCASTER_MANASPELL  1088
#define IDC_TOOL_SPELLCASTER_MANA_SPELL 1088
#define IDC_TOOL_SPELLCASTER_HPBELOW    1089
#define IDC_TOOL_SPELLCASTER_LIFE_HP    1089
#define IDC_TOOL_SPELLCASTER_LIFESPELL  1090
#define IDC_TOOL_SPELLCASTER_LIFE_SPELL 1090
#define IDC_TOOL_SPELLCASTER_SUMMON_LESSTHAN 1091
#define IDC_TOOL_SPELLCASTER_SUMMON_NAME 1092
#define IDC_TOOL_SPELLCASTER_SUMMON_MANA 1093
#define IDC_TOOL_SPELLCASTER_MANA_SPELL_MANA 1094
#define IDC_TOOL_SPELLCASTER_STRIKE     1094
#define IDC_TOOL_SPELLCASTER_LIFE_SPELL_MANA 1095
#define IDC_TOOL_SPELLCASTER_STRIKE_MANA 1096
#define IDC_TOOL_SPELLCASTER_STRIKE_SPELL_DEFAULT 1097
#define IDC_TOOL_SPELLCASTER_STRIKE_SPELL_DEFAULT_HP_MIN 1098
#define IDC_TOOL_SPELLCASTER_LOGIC      1100
#define IDC_TOOL_SPELLCASTER_ALARM      1101
#define IDC_TOOL_SPELLCASTER_EXURA_LIFE 1101
#define IDC_TOOL_SPELLCASTER_GRAN_LIFE  1102
#define IDC_TOOL_SPELLCASTER_VITA_LIFE  1103
#define IDC_TOOL_SPELLCASTER_EXURA_MANA 1104
#define IDC_TOOL_SPELLCASTER_GRAN_MANA  1105
#define IDC_TOOL_SPELLCASTER_VITA_MANA  1106
#define IDC_TOOL_SPELLCASTER_MIN_POISON_DAMAGE 1107
#define IDD_CONFIG                      3000
#define IDC_ENABLE                      3004
#define IDC_TOOL_SPELLCASTER_MANA1      3014
#define IDC_TOOL_SPELLCASTER_LIFE       3015
#define IDC_TOOL_SPELLCASTER_SUMMON     3016
#define IDC_TOOL_SPELLCASTER_FLAM       3017
#define IDC_TOOL_SPELLCASTER_FRIGO      3018
#define IDC_TOOL_SPELLCASTER_MORT       3019
#define IDC_TOOL_SPELLCASTER_TERA       3020
#define IDC_TOOL_SPELLCASTER_VIS        3021
#define IDC_TOOL_SPELLCASTER_CUSTOM     3025
#define IDC_TOOL_SPELLCASTER_EXURA      3026
#define IDC_TOOL_SPELLCASTER_GRAN       3027
#define IDC_TOOL_SPELLCASTER_VITA       3028
#define IDC_TOOL_SPELLCASTER_HEAL_PARALYSIS 3029
#define IDC_TOOL_SPELLCASTER_HEAL_POISON 3030

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        3008
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         3031
#define _APS_NEXT_SYMED_VALUE           3000
#endif
#endif
