//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by mod_spellcaster.rc
//
#define IDC_TOOL_SPELLCASTER_MANA       1086
#define IDC_TOOL_SPELLCASTER_MANA_MANA  1087
#define IDC_TOOL_SPELLCASTER_SPELL      1088
#define IDC_TOOL_SPELLCASTER_MANASPELL  1088
#define IDC_TOOL_SPELLCASTER_MANA_SPELL 1088
#define IDC_TOOL_SPELLCASTER_HPBELOW    1089
#define IDC_TOOL_SPELLCASTER_LIFE_HP    1089
#define IDC_TOOL_SPELLCASTER_LIFESPELL  1090
#define IDC_TOOL_SPELLCASTER_LIFE_SPELL 1090
#define IDC_SUMMON_LESSTHAN             1091
#define IDC_TOOL_SPELLCASTER_SUMMON_LESSTHAN 1091
#define IDC_SUMMON_NAME                 1092
#define IDC_TOOL_SPELLCASTER_SUMMON_NAME 1092
#define IDC_SUMMON_MANA                 1093
#define IDC_TOOL_SPELLCASTER_SUMMON_MANA 1093
#define IDC_TOOL_SPELLCASTER_MANA_SPELL_MANA 1094
#define IDC_TOOL_SPELLCASTER_LIFE_SPELL_MANA 1095
#define IDC_TOOL_SPELLCASTER_LOGIC      1100
#define IDC_TOOL_SPELLCASTER_ALARM      1101
#define IDC_TOOL_FLUIDDRINKER_HPBELOW   1113
#define IDC_TOOL_FLUIDDRINKER_MANABELOW 1114
#define IDC_TOOL_FLUIDDRINKER_DRINKMANA 1115
#define IDC_TOOL_FLUIDDRINKER_DRINKHP   1116
#define IDC_TOOL_FLUIDDRINKER_SLEEP     1118
#define IDC_TOOL_FLUIDDRINKER_HOTKEY_LIFE 1143
#define IDC_TOOL_FLUIDDRINKER_HOTKEY_MANA 1144
#define IDC_TOOL_FLUIDDRINKER_DROPEMPTY 1176
#define IDD_CONFIG                      3000
#define IDC_CONTAINER_MODE_1            3000
#define IDC_CONTAINER_STATUS            3001
#define IDC_CONTAINER_STATUS1           3001
#define IDC_CONTAINER_MODE_2            3002
#define IDC_CONTAINER_STATUS2           3003
#define IDC_ENABLE                      3004
#define IDC_AUTO_OPEN                   3005
#define IDC_CONTAINER_MODE_3            3006
#define IDC_CONTAINER_STATUS3           3007
#define IDC_CONTAINER_MODE_4            3008
#define IDC_CONTAINER_STATUS4           3009
#define IDC_LOOT_FOOD                   3010
#define IDC_LOOT_GP                     3011
#define IDC_CONTAINER_MODE_5            3012
#define IDC_CONTAINER_STATUS5           3013
#define IDC_CONTAINER_MODE_6            3014
#define IDC_TOOL_SPELLCASTER_MANA1      3014
#define IDC_CONTAINER_STATUS6           3015
#define IDC_TOOL_SPELLCASTER_LIFE       3015
#define IDC_CONTAINER_MODE_7            3016
#define IDC_TOOL_SPELLCASTER_SUMMON     3016
#define IDC_CONTAINER_STATUS7           3017
#define IDC_CONTAINER_MODE_8            3018
#define IDC_CONTAINER_STATUS8           3019
#define IDC_CONTAINER_MODE_9            3020
#define IDC_CONTAINER_STATUS9           3021
#define IDC_LOOT_CUSTOM                 3022
#define IDC_LOOT_WORMS                  3023
#define IDC_CONTAINER_MODE_10           3024
#define IDC_CONTAINER_STATUS10          3025

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        3002
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         3015
#define _APS_NEXT_SYMED_VALUE           3000
#endif
#endif
