//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by mod_autogo.rc
//
#define IDS_BEGIN                       1
#define IDS_SKILL                       2
#define IDS_RESOURCE                    3
#define IDS_PROXIMITY                   4
#define IDS_ITEM                        5
#define IDS_GENERAL                     6
#define IDS_SKILL_ALL                   7
#define IDS_SKILL_LEVEL                 8
#define IDS_SKILL_MAGICLVL              9
#define IDS_SKILL_FISHING               10
#define IDS_SKILL_FIST                  11
#define IDS_SKILL_CLUB                  12
#define IDS_SKILL_SWORD                 13
#define IDS_SKILL_AXE                   14
#define IDS_SKILL_DISTANCE              15
#define IDS_SKILL_SHIELDING             16
#define IDS_RESOURCE_HP                 17
#define IDS_RESOURCE_MP                 18
#define IDS_RESOURCE_SP                 19
#define IDS_RESOURCE_STAMINA            20
#define IDS_RESOURCE_CAPACITY           21
#define IDS_RESOURCE_SPACE              22
#define IDS_ITEM_FOOD                   23
#define IDS_ITEM_CUSTOM                 24
#define IDS_PROXIMITY_PLAYER            25
#define IDS_PROXIMITY_MONSTER           26
#define IDS_PROXIMITY_GM                27
#define IDS_PROXIMITY_BATTLELIST        28
#define IDS_PROXIMITY_SKULL             29
#define IDS_GENERAL_ALLMESSAGES         30
#define IDS_MESSAGE_ALLMESSAGES         30
#define IDS_GENERAL_PUBLICMESSAGES      31
#define IDS_MESSAGE_PUBLICMESSAGES      31
#define IDS_GENERAL_PRIVATEMESSAGES     32
#define IDS_MESSAGE_PRIVATEMESSAGES     32
#define IDS_GENERAL_CHARACTERMOVED      33
#define IDS_GENERAL_STATUSFLAG          34
#define IDS_GENERAL_WAYPOINTREACHED     34
#define IDS_BEGIN_ATTRIBUTE             35
#define IDS_LEVELUP                     36
#define IDS_PERCLVLACHIEVED             37
#define IDS_PERCLVLREMAINING            38
#define IDS_CONDITION                   39
#define IDS_EQUAL                       40
#define IDS_LESS                        41
#define IDS_MORE                        42
#define IDS_APPEARS                     43
#define IDS_NEARBY                      43
#define IDS_DISAPPEARS                  44
#define IDS_ISONSCREENFOR               45
#define IDS_KILL                        46
#define IDS_SHUTDOWN                    47
#define IDS_RUNAWAY                     48
#define IDS_START                       49
#define IDS_DEPOT                       50
#define IDS_SPELL                       51
#define IDS_SCREENSHOT                  52
#define IDS_SUSPEND_MODULES             53
#define IDS_START_MODULES               54
#define IDS_SOUND                       55
#define IDS_STOPWALKING                 56
#define IDS_LOGOUT                      57
#define IDS_MAXIMIZE                    58
#define IDS_WINDOW_ACTION               58
#define IDS_LOG_EVENTS                  59
#define IDS_FROMALL                     60
#define IDS_FROM                        61
#define IDS_CONTAINS                    62
#define IDS_RESOURCE_XP                 63
#define IDS_PROXIMITY_VIPONLINE         64
#define IDS_MESSAGE                     64
#define IDS_ONLINE                      65
#define IDS_ONLINE_CURRENT_PLAYER       66
#define IDS_ONLINE_NONE                 67
#define IDS_ONLINE_HEART                68
#define IDS_ONLINE_SKULL                69
#define IDS_ONLINE_LIGHTNING            70
#define IDS_ONLINE_RETICLE              71
#define IDS_ONLINE_STAR                 72
#define IDS_ONLINE_YINYANG              73
#define IDS_ONLINE_TRIPOINT             74
#define IDS_ONLINE_X                    75
#define IDS_ONLINE_DOLLARSIGN           76
#define IDS_ONLINE_IRONCROSS            77
#define IDS_LOGON                       78
#define IDS_LOGOFF                      79
#define IDS_PROXIMITY_SKULL_BLACK       80
#define IDS_PROXIMITY_SKULL_RED         81
#define IDS_PROXIMITY_SKULL_GREEN       82
#define IDS_PROXIMITY_SKULL_WHITE       83
#define IDS_PROXIMITY_SKULL_YELLOW      84
#define IDS_STATUS                      85
#define IDS_STATUS_POISONED             86
#define IDS_STATUS_BURNING              87
#define IDS_STATUS_ELECTRIFIED          88
#define IDS_STATUS_DRUNK                89
#define IDS_STATUS_MANASHIELD           90
#define IDS_STATUS_SLOWED               91
#define IDS_STATUS_HASTED               92
#define IDS_STATUS_FREEZING             93
#define IDS_STATUS_DROWNING             94
#define IDS_STATUS_DAZZLED              95
#define IDS_STATUS_CURSED               96
#define IDS_STATUS_STRENGTHENED         97
#define IDS_STATUS_LOGOUTBLOCK          98
#define IDS_STATUS_PZBLOCK              99
#define IDS_STATUS_INPZ                 100
#define IDS_ALARM_TYPE_ERROR            101
#define IDS_ATTRIBUTE_ERROR             102
#define IDS_CONDITION_ERROR             103
#define IDS_TRIGGER_ERROR               104
#define IDS_SPELLWORDS_ERROR            105
#define IDS_SOUNDFILE_ERROR             106
#define IDS_SCREENSHOT_ERROR            107
#define IDS_GENERAL_CHARACTERHIT        108
#define IDS_WINDOWACTION_ERROR          109
#define IDS_GENERAL_CHARACTERNOTMOVED   110
#define IDS_START_RUNAWAY               111
#define IDS_PRESENT                     112
#define IDS_ABSENT                      113
#define IDS_ONLINE_VIP_PLAYER           114
#define IDS_PROXIMITY_ATTACKINGPLAYER   115
#define IDS_PERSISTENT                  116
#define IDS_PERMANENT                   117
#define IDC_AUTOGO_TRIGGER              1046
#define IDC_AUTOGO_ACTION               1047
#define IDC_AUTOGO_RUNAWAY_X            1048
#define IDC_AUTOGO_RUNAWAY_Y            1049
#define IDC_AUTOGO_RUNAWAY_Z            1050
#define IDC_AUTOGO_ACT_X                1051
#define IDC_AUTOGO_ACT_Y                1052
#define IDC_AUTOGO_ACT_Z                1053
#define IDC_AUTOGO_CUR_X                1055
#define IDC_AUTOGO_CUR_Y                1056
#define IDC_AUTOGO_CUR_Z                1057
#define IDC_AUTOGO_TORUNAWAY            1060
#define IDC_AUTOGO_TOSTART              1061
#define IDC_TOOL_FLUIDDRINKER_HPBELOW   1113
#define IDC_TOOL_FLUIDDRINKER_MANABELOW 1114
#define IDC_TOOL_FLUIDDRINKER_DRINKMANA 1115
#define IDC_TOOL_FLUIDDRINKER_DRINKHP   1116
#define IDC_TOOL_FLUIDDRINKER_SLEEP     1118
#define IDC_TOOL_FLUIDDRINKER_HOTKEY_LIFE 1143
#define IDC_TOOL_FLUIDDRINKER_HOTKEY_MANA 1144
#define IDC_TOOL_FLUIDDRINKER_DROPEMPTY 1176
#define IDD_CONFIG                      3000
#define IDC_CONTAINER_MODE_1            3000
#define IDC_CONTAINER_STATUS            3001
#define IDC_CONTAINER_STATUS1           3001
#define IDC_CONTAINER_MODE_2            3002
#define IDC_CONTAINER_STATUS2           3003
#define IDD_WHITELIST                   3003
#define IDC_ENABLE                      3004
#define IDC_AUTO_OPEN                   3005
#define IDC_CONTAINER_MODE_3            3006
#define IDB_FIRE                        3006
#define IDC_CONTAINER_STATUS3           3007
#define IDB_ENERGY                      3007
#define IDC_CONTAINER_MODE_4            3008
#define IDB_BATTLE                      3008
#define IDC_CONTAINER_STATUS4           3009
#define IDB_POISON                      3009
#define IDC_LOOT_FOOD                   3010
#define IDC_LOOT_GP                     3011
#define IDC_AUTOGO_BATTLELIST           3011
#define IDC_AUTOGO_TRIGGERBATTLELIST    3011
#define IDC_CONTAINER_MODE_5            3012
#define IDC_AUTOGO_ATTACKSIGN           3012
#define IDC_AUTOGO_TRIGGERSIGN          3012
#define IDB_BLACK                       3012
#define IDC_CONTAINER_STATUS5           3013
#define IDC_AUTOGO_PLAYER               3013
#define IDC_AUTOGO_BATTLEPLAYER         3013
#define IDB_GREEN                       3013
#define IDC_CONTAINER_MODE_6            3014
#define IDC_AUTOGO_MONSTER              3014
#define IDC_AUTOGO_BATTLEMONSTER        3014
#define IDC_CONTAINER_STATUS6           3015
#define IDC_AUTOGO_PRVMSG               3015
#define IDC_AUTOGO_TRIGGERMESSAGE       3015
#define IDB_RED                         3015
#define IDC_CONTAINER_MODE_7            3016
#define IDC_AUTOGO_PUBMSG               3016
#define IDC_AUTOGO_TRIGGERSKULL         3016
#define IDB_WHITE                       3016
#define IDC_CONTAINER_STATUS7           3017
#define IDC_AUTOGO_PARANOIA             3017
#define IDC_AUTOGO_BATTLEPARANOIA       3017
#define IDC_AUTOGO_BATTELIST            3017
#define IDB_YELLOW                      3017
#define IDC_CONTAINER_MODE_8            3018
#define IDC_AUTOGO_OTHERSIGN            3018
#define IDC_AUTOGO_TRIGGERVIP           3018
#define IDI_SPEAKER                     3018
#define IDC_CONTAINER_STATUS8           3019
#define IDC_AUTOGO_WHITELIST            3019
#define IDC_AUTOGO_BATTLEWHITELIST      3019
#define IDI_SPEAKER2                    3019
#define IDC_CONTAINER_MODE_9            3020
#define IDC_AUTOGO_HPLOSS               3020
#define IDC_WHITELIST_LIST              3020
#define IDC_AUTOGO_TRIGGERHPLOSS        3020
#define IDD_ALARM_DIALOG                3020
#define IDC_CONTAINER_STATUS9           3021
#define IDC_AUTOGO_MOVE                 3021
#define IDC_WHITELIST_NAME              3021
#define IDC_AUTOGO_TRIGGERMOVE          3021
#define IDD_GENERAL_CONFIG_DIALOG       3021
#define IDC_LOOT_CUSTOM                 3022
#define IDC_AUTOGO_NOSOUL               3022
#define IDC_WHITELIST_ADD               3022
#define IDC_AUTOGO_TRIGGERSOULPOINTS    3022
#define IDC_LOOT_WORMS                  3023
#define IDC_AUTOGO_NOBLANK              3023
#define IDC_WHITELIST_DELETE            3023
#define IDC_AUTOGO_TRIGGERBLANK         3023
#define IDC_CONTAINER_MODE_10           3024
#define IDC_AUTOGO_SHADOWALARM          3024
#define IDC_AUTOGO_TRIGGERHPBELOW       3024
#define IDC_CONTAINER_STATUS10          3025
#define IDC_AUTOGO_STATUS               3025
#define IDB_COLUMN_HEADERS              3025
#define IDC_AUTOGO_NOCAPACITY           3026
#define IDC_AUTOGO_TRIGGERCAPACITY      3026
#define IDC_AUTOGO_NOSPACE              3027
#define IDC_AUTOGO_BATTLEPARANOIAM      3027
#define IDB_VIP                         3027
#define IDC_AUTOGO_NOFOOD               3028
#define IDC_AUTOGO_TRIGGEROUTOF         3028
#define IDC_AUTOGO_ACTIONBATTLELIST     3029
#define IDC_AUTOGO_ACTIONBATTLELIST_PLAYER 3029
#define IDB_GENERAL                     3029
#define IDC_AUTOGO_ACTIONSIGN           3030
#define IDB_PROXIMITY                   3030
#define IDC_AUTOGO_ACTIONMESSAGE        3031
#define IDB_SCREENSHOT                  3031
#define IDC_AUTOGO_TRIGGERHPABOVE       3032
#define IDB_ATTACK                      3032
#define IDC_AUTOGO_ACTIONBATTLELIST_MONSTER 3033
#define IDB_AUDIO                       3033
#define IDC_AUTOGO_ACTIONHPLOSS         3034
#define IDB_BLANK                       3034
#define IDC_AUTOGO_ACTIONMOVE           3035
#define IDB_SPELL                       3035
#define IDC_AUTOGO_ACTIONSOULPOINT      3036
#define IDB_DEPOT                       3036
#define IDC_AUTOGO_ACTIONBLANK          3037
#define IDB_KILLTIBIA                   3037
#define IDC_AUTOGO_ACTIONCAPACITY       3038
#define IDB_LOGEVENTS                   3038
#define IDC_AUTOGO_SOUNDBATTLELIST      3039
#define IDC_AUTOGO_SOUNDBATTLELIST_PLAYER 3039
#define IDB_LOGOUT                      3039
#define IDC_AUTOGO_SOUNDSIGN            3040
#define IDB_MAXIMIZE                    3040
#define IDC_AUTOGO_ACTIONHPBELOW        3041
#define IDB_RUNAWAY                     3041
#define IDC_AUTOGO_ACTIONOUTOF          3042
#define IDC_AUTOGO_ACTIONOUTOF_FOOD     3042
#define IDB_SHUTDOWN                    3042
#define IDC_AUTOGO_SOUNDMESSAGE         3043
#define IDB_START                       3043
#define IDC_AUTOGO_ACTIONBATTLELIST_GM  3044
#define IDB_STARTMODULE                 3044
#define IDC_AUTOGO_ACTIONBATTLELIST_LIST 3045
#define IDB_SUSPENDMODULE               3045
#define IDC_AUTOGO_SOUNDHPLOSS          3046
#define IDR_UHOH                        3046
#define IDC_AUTOGO_SOUNDMOVE            3047
#define IDC_AUTOGO_SOUNDSOULPOINT       3048
#define IDC_AUTOGO_SOUNDBLANK           3049
#define IDC_AUTOGO_SOUNDCAPACITY        3050
#define IDB_ITEMS                       3050
#define IDC_AUTOGO_SOUNDHPBELOW         3051
#define IDD_ADD_CUSTOM_SPELL            3051
#define IDC_AUTOGO_SOUNDOUTOF           3052
#define IDC_AUTOGO_SOUNDOUTOF_FOOD      3052
#define IDC_AUTOGO_CAPACITY             3053
#define IDC_AUTOGO_SOULPOINT            3054
#define IDB_STOP                        3054
#define IDC_AUTOGO_BLANK                3055
#define IDC_AUTOGO_BATTLEGM             3056
#define IDC_AUTOGO_HPBELOW              3057
#define IDC_AUTOGO_OUTOFFOOD            3058
#define IDC_AUTOGO_OUTOFWORMS           3059
#define IDC_AUTOGO_ACTIONOUTOF_SPACE    3059
#define IDC_AUTOGO_SIGNBATTLE           3060
#define IDC_AUTOGO_SIGNPOISON           3061
#define IDC_AUTOGO_SIGNFIRE             3062
#define IDC_AUTOGO_SIGNENERGY           3063
#define IDC_AUTOGO_MESSAGEPRIVATE       3064
#define IDC_AUTOGO_MESSAGEPUBLIC        3065
#define IDC_AUTOGO_OUTOFSPACE           3066
#define IDC_AUTOGO_ACT_DIRECTION        3067
#define IDC_AUTOGO_SOUNDBATTLELIST_MONSTER 3068
#define IDC_AUTOGO_SOUNDBATTLELIST_GM   3069
#define IDC_AUTOGO_HPABOVE              3070
#define IDC_AUTOGO_SOUNDBATTLELIST_LIST 3071
#define IDC_AUTOGO_MESSAGE_IGNORE_SPELLS 3072
#define IDC_AUTOGO_ACTIONHPABOVE        3073
#define IDC_AUTOGO_SOUNDHPABOVE         3074
#define IDC_AUTOGO_TRIGGERSOULPOINTS_ABOVE 3075
#define IDC_AUTOGO_SOULPOINT_ABOVE      3076
#define IDC_AUTOGO_ACTIONSOULPOINT_ABOVE 3077
#define IDC_AUTOGO_SOUNDSOULPOINT_ABOVE 3078
#define IDC_AUTOGO_TRIGGERMANABELOW     3079
#define IDC_AUTOGO_MANABELOW            3080
#define IDC_AUTOGO_ACTIONMANABELOW      3081
#define IDC_AUTOGO_SOUNDMANABELOW       3082
#define IDC_AUTOGO_TRIGGERMANAABOVE     3083
#define IDC_AUTOGO_MANAABOVE            3084
#define IDC_AUTOGO_ACTIONMANAABOVE      3085
#define IDC_AUTOGO_SOUNDMANAABOVE       3086
#define IDC_AUTOGO_RUNAWAY_REACHED      3087
#define IDC_AUTOGO_RUNAWAY_REACHED_RADIUS 3088
#define IDC_AUTOGO_ACTIONRUNAWAY_REACHED 3089
#define IDC_AUTOGO_SOUNDRUNAWAY_REACHED 3090
#define IDC_AUTOGO_OUTOFCUSTOM          3091
#define IDC_HPBELOW_UNTIL_RECOVERY      3092
#define IDC_MANABELOW_UNTIL_RECOVERY    3093
#define IDC_AUTOGO_SOUNDOUTOF_SPACE     3094
#define IDC_AUTOGO_ACTIONOUTOF_CUSTOM   3095
#define IDC_AUTOGO_SOUNDOUTOF_CUSTOM    3096
#define IDC_WHITELIST_MKBLACK           3096
#define IDC_AUTOGO_ACTIONOUTOF_CUSTOM_ITEM 3097
#define IDC_AUTOGO_BATTLEANXIETY        3098
#define IDC_AUTOGO_ACTIONSKULL          3099
#define IDC_AUTOGO_SOUNDSKULL           3100
#define IDC_AUTOGO_SKULLWHITE           3101
#define IDC_AUTOGO_SKULLRED             3102
#define IDC_AUTOGO_SKULLYELLOW          3103
#define IDC_AUTOGO_SKULLGREEN           3104
#define IDC_AUTOGO_SKULLBLACK           3105
#define IDC_AUTOGO_TRIGGERSTAMINA       3106
#define IDC_AUTOGO_STAMINA              3107
#define IDC_AUTOGO_ACTIONSTAMINA        3108
#define IDC_AUTOGO_SOUNDSTAMINA         3109
#define IDC_AUTOGO_TRIGGERSTAMINA_ABOVE2 3110
#define IDC_AUTOGO_TRIGGERSTAMINA_ABOVE 3110
#define IDC_AUTOGO_STAMINA_ABOVE        3111
#define IDC_AUTOGO_ACTIONSTAMINA_ABOVE  3112
#define IDC_AUTOGO_SOUNDSTAMINA_ABOVE   3113
#define IDC_AUTOGO_ACTIONVIP            3114
#define IDC_AUTOGO_SOUNDVIP             3115
#define IDC_FRAME_TRIGGER_OPTIONS       3116
#define IDC_FRAME_WHITE_LIST            3117
#define IDC_ALARM_FRAME                 3118
#define IDC_ALARM_TYPE                  3119
#define IDC_ATTRIBUTE                   3120
#define IDC_CONDITION                   3121
#define IDC_ACTION_FRAME                3123
#define IDC_ACTION_RUNAWAY              3124
#define IDC_ACTION_START                3125
#define IDC_ACTION_DEPOT                3126
#define IDC_ACTION_STOPWAKING           3127
#define IDC_ACTION_LOGOUT               3128
#define IDC_ACTION_KILL                 3129
#define IDC_ACTION_SHUTDOWN             3130
#define IDC_ACTION_SCREENSHOT           3131
#define IDC_SCREENSHOT_OPTIONS          3132
#define IDC_ACTION_STOP_WALKING         3133
#define IDC_AUDIO_FILE                  3134
#define IDC_ACTION_SOUND                3135
#define IDC_ACTION_SUSPEND              3136
#define IDC_ACTION_SUSPEND_MODULES      3136
#define IDC_ALARM_ADD                   3137
#define IDC_ALARM_EDIT                  3138
#define IDC_ALARM_DELETE                3139
#define IDC_ALARM_LIST                  3140
#define IDC_ACTION_SPELL                3141
#define IDC_SPELL_LIST                  3142
#define IDC_TRIGGER                     3143
#define IDC_MODULES_LIST                3144
#define IDC_TAB_CONTROL                 3145
#define IDC_ACTION_START_MODULES        3147
#define IDC_INSTRUCTION_TEXT            3148
#define IDC_MODULES_LIST2               3149
#define IDC_ACTION_LOG_EVENTS           3150
#define IDC_ACTION_MAXIMIZE             3151
#define IDC_ACTION_WINDOW               3151
#define IDC_GENERAL_CONFIG_FRAME        3152
#define IDC_GENERAL_CONFIG_MESSAGE_OPTIONS_FRAME 3153
#define IDC_GENERAL_CONFIG_PROXIMITY_OPTIONS_FRAME 3154
#define IDC_GENERAL_CONFIG_POSITION_OPTIONS_FRAME 3155
#define IDC_MAINTAIN_POS              3156
#define IDC_RUNAWAY_PICTURE             3158
#define IDC_START_PICTURE               3159
#define IDC_SPELLWORDS                  3160
#define IDC_REQUIRED_MANA               3161
#define IDC_CASTING_DELAY               3162
#define IDC_SPELL_CONFIGURATION_FRAME   3163
#define IDC_ACTION_WINDOW_LIST          3164
#define IDC_FLASHONALARM                3165
#define IDC_AUTOGO_MODPRIORITY          3166
#define IDC_ACTION_PERSISTENT           3167
#define IDC_ACTION_PERMANENT            3168
#define IDB_PERSISTENT                  3169
#define IDB_PERMANENT                   3170

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        3056
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         3168
#define _APS_NEXT_SYMED_VALUE           3000
#endif
#endif
