//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by mod_fluid.rc
//
#define IDC_TOOL_FLUIDDRINKER_HPBELOW   1113
#define IDC_TOOL_FLUIDDRINKER_MANABELOW 1114
#define IDC_TOOL_FLUIDDRINKER_DRINKMANA 1115
#define IDC_TOOL_FLUIDDRINKER_DRINKHP   1116
#define IDC_TOOL_FLUIDDRINKER_SLEEP     1118
#define IDC_TOOL_FLUIDDRINKER_HPBELOW_N 1120
#define IDC_TOOL_FLUIDDRINKER_DRINKHP_N 1121
#define IDC_TOOL_FLUIDDRINKER_HPBELOW_S 1122
#define IDC_TOOL_FLUIDDRINKER_DRINKHP_S 1123
#define IDC_TOOL_FLUIDDRINKER_HPBELOW_G 1124
#define IDC_TOOL_FLUIDDRINKER_DRINKHP_G 1125
#define IDC_TOOL_FLUIDDRINKER_HPBELOW_H 1126
#define IDC_TOOL_FLUIDDRINKER_DRINKHP_H 1127
#define IDC_TOOL_FLUIDDRINKER_MANABELOW_N 1128
#define IDC_TOOL_FLUIDDRINKER_DRINKMANA_N 1129
#define IDC_TOOL_FLUIDDRINKER_MANABELOW_S 1130
#define IDC_TOOL_FLUIDDRINKER_DRINKMANA_S 1131
#define IDC_TOOL_FLUIDDRINKER_MANABELOW_G 1132
#define IDC_TOOL_FLUIDDRINKER_DRINKMANA_G 1133
#define IDC_CUSTOM_ITEM_1_BELOW         1134
#define IDC_CUSTOM_ITEM_1_USE           1135
#define IDC_CUSTOM_ITEM_2_BELOW         1136
#define IDC_CUSTOM_ITEM_2_USE           1137
#define IDC_TOOL_FLUIDDRINKER_DRINKHP_U 1138
#define IDC_TOOL_FLUIDDRINKER_HPBELOW_U 1139
#define IDC_TOOL_FLUIDDRINKER_HOTKEY_LIFE 1143
#define IDC_TOOL_FLUIDDRINKER_HOTKEY_MANA 1144
#define IDC_TOOL_FLUIDDRINKER_DROPEMPTY 1176
#define IDC_TOOL_RANDOMCAST             1177
#define IDC_TOOL_USEHOTKEY              1178
#define IDD_CONFIG                      3000
#define IDC_CONTAINER_MODE_1            3000
#define IDC_CONTAINER_STATUS            3001
#define IDC_CONTAINER_STATUS1           3001
#define IDC_CONTAINER_MODE_2            3002
#define IDC_CONTAINER_STATUS2           3003
#define IDC_ENABLE                      3004
#define IDC_AUTO_OPEN                   3005
#define IDC_CONTAINER_MODE_3            3006
#define IDC_CONTAINER_STATUS3           3007
#define IDC_CONTAINER_MODE_4            3008
#define IDC_CONTAINER_STATUS4           3009
#define IDC_LOOT_FOOD                   3010
#define IDC_LOOT_GP                     3011
#define IDC_CHECK1                      3011
#define IDC_CONTAINER_MODE_5            3012
#define IDC_FRAME_HEALTH_RECOVERY       3012
#define IDC_CONTAINER_STATUS5           3013
#define IDC_FRAME_MANA_RECOVERY         3013
#define IDC_CONTAINER_MODE_6            3014
#define IDC_FRAME_GENERAL_OPTIONS       3014
#define IDC_CONTAINER_STATUS6           3015
#define IDC_CONTAINER_MODE_7            3016
#define IDC_CONTAINER_STATUS7           3017
#define IDC_CONTAINER_MODE_8            3018
#define IDC_CONTAINER_STATUS8           3019
#define IDC_CONTAINER_MODE_9            3020
#define IDC_CONTAINER_STATUS9           3021
#define IDC_CUSTOM_ITEM_1               3021
#define IDC_LOOT_CUSTOM                 3022
#define IDC_CUSTOM_ITEM_2               3022
#define IDC_LOOT_WORMS                  3023
#define IDC_CONTAINER_MODE_10           3024
#define IDC_CONTAINER_STATUS10          3025

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        3002
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         3015
#define _APS_NEXT_SYMED_VALUE           3000
#endif
#endif
